spring.application.name=sb3
server.port=8088

general.llm.default=CLOUD_GIGA_CHAT_2

cloudru.base.url=https://foundation-models.api.cloud.ru
cloudru.authorization.key=${CLOUDRU_AUTHORIZATION_KEY}
gigachat.base.url=https://gigachat.devices.sberbank.ru/api/v1/chat/completions
gigachat.auth.url=https://ngw.devices.sberbank.ru:9443/api/v2/oauth
gigachat.llm.model=GIGACHAT_2_MAX


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sb3_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jackson.property-naming-strategy=SNAKE_CASE

spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger

logging.level.root=info
logging.level.org.springframework.web.client.RestClient=DEBUG
logging.level.org.springframework.http.client=TRACE
logging.level.org.springframework.web.HttpLogging=TRACE
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
logging.level.liquibase=DEBUG




# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refresh-expiration=604800


BACKEND_USERNAME=agent
BACKEND_PASSWORD=agent-secret-password
