spring.application.name=sb3
server.port=8088

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sb3_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

springdoc.swagger-ui.path=/swagger

logging.level.root=info

spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
logging.level.liquibase=DEBUG
spring.liquibase.enabled=true
