spring.application.name=sb3
server.port=8088

general.llm.default=GIGA_CHAT

cloudru.base.url=https://foundation-models.api.cloud.ru/v1/chat/completions
cloudru.authorization.key=${CLOUDRU_AUTHORIZATION_KEY}
gigachat.base.url=https://gigachat.devices.sberbank.ru/api/v1/chat/completions
gigachat.auth.url=https://ngw.devices.sberbank.ru:9443/api/v2/oauth


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sb3_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

springdoc.swagger-ui.path=/swagger

logging.level.root=info

spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
logging.level.liquibase=DEBUG
#spring.jackson.serialization.write-dates-as-timestamps=false
spring.liquibase.enabled=true
